version: '3.8'
# env vars in .env
services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db-stuff/init/:/docker-entrypoint-initdb.d/
    env_file:
      - .env
    networks:
      - pg-net

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    volumes:
      - "./db-stuff/servers.json:/pgadmin4/servers.json"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - pg-net

volumes:
  postgres_data:

networks:
  pg-net:
    driver: bridge
